### ISSUE TITLE
已经无法搜索了，sfile get也不work了，看到一个多月前的issue也没人处理了。。。国人服务加油呀

### ISSUE THREAD

**Issue by Tairraos** [staticfile/static#333]
$sfile get jQuery
 未找到库: jQuery
/usr/local/lib/node_modules/sfile/bin/sfile:88
        if (suggest.length > 0) {
                   ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/sfile/bin/sfile:88:20
    at Request._callback (/usr/local/lib/node_modules/sfile/lib/index.js:15:28)
    at Request.self.callback (/usr/local/lib/node_modules/sfile/node_modules/request/request.js:129:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/sfile/node_modules/request/request.js:873:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/sfile/node_modules/request/request.js:824:12)
    at emitNone (events.js:72:20)

**Comment by Gavin-YYC** [comment]
现在依然无法搜索。。。

**Comment by liudanking** [comment]
依然挂着+1

**Comment by starsea** [comment]
七牛这是怎么了。。。。。。

**Comment by TechQuery** [comment]
国猿身不由己啊 —— https://github.com/staticfile/static/issues/337#issuecomment-222339464
